spring:
  main:
    banner-mode: "off"
  profiles:
    active: default
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@DB_SERVICE_high?TNS_ADMIN=/PATH/TO/WALLET
    username: ADMIN
    password: "PASSWORD"
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      sql-for-validate-connection: SELECT * FROM dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 5
      min-pool-size: 5
      max-pool-size: 10
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2MB
oracle:
  jdbc:
    fanEnabled: true

genai:
  region: "US_CHICAGO_1"
  config:
    location: "~/.oci/config"
    profile: "DEFAULT"
  compartment_id: "COMPARTMENT_ID"
  chat_model_id: "ocid1.generativeaimodel.AAAAAAAAAAAAA"
  summarization_model_id: "ocid1.generativeaimodel.AAAAAAAAAAAAA"
  embed_model_id: "cohere.embed-english-v3.0"
storage:
  path: "/PATH/FOR/UPLOAD/FILES"
logging:
  level:
    com.oracle.bmc.generativeai.model.ModelCapability: ERROR
